### ISSUE TITLE
whence in PttLock should be SEEK_SET? (or PttLock after lseek should set offset as 0?)

### ISSUE THREAD

**Issue by chhsiao1981** [ptt/pttbbs#100]
https://github.com/ptt/pttbbs/blob/master/common/sys/lock.c#L15

Found several lines using PttLock while already did lseek.
(but some didnt use lseek before PttLock)

Not exactly sure whether offset of lseek is the same as the fnctl,
and not exactly sure whether fcntl F_SETLKW affects seek-pointer though.

The following lines use PttLock F_WRLCK

https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L84 (after lseek)
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L133 (after lseek)
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L195 (no lseek)
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L261 (no lseek)

The following lines use PttLock F_UNLCK
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L86 (after lseek)
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L149 (after lseek)
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L223 (after lseek)
https://github.com/ptt/pttbbs/blob/master/common/sys/record.c#L275 (after lseek)

**Comment by chhsiao1981** [comment]
strangely there are lseek between F_WRLCK / F_UNLCK in the following functions:

record.substitute_record2
record.delete_records
record. delete_record2

Not exactly sure whether it's just that I didn't fully know fnctl / lseek mechanism,
or we do need to change to SEEK_SET in PttLock.

**Comment by chhsiao1981** [comment]
The reason why record.substitute_record2 works is because lseek is SEEK_SET to same offset before F_WRLCK

The reason why record.delete_records, record.delete_record2 work is because the fd is closed after unlock.
(lock is released and no deadlock.)

**Comment by wens** [comment]
Based on the usage patterns you listed, which covers about everything, we should probably be using SEEK_SET in PttLock.

**Comment by chhsiao1981** [comment]
resolved in #101
