### ISSUE TITLE
請問如何找回ID和密碼

### ISSUE THREAD

**Issue by hijkzzz** [ptt/pttbbs#103]
郵箱可訪問，或者請幫忙註銷 r08944053@ntu.edu.tw 重新註冊

**Comment by holishing** [comment]
ID_GetBack 板置底公告自己看一看，這邊是討論程式問題的地方，且處理帳號事務的人也不會看這邊

**Comment by hijkzzz** [comment]
> ID_GetBack 板置底公告自己看一看，這邊是討論程式問題的地方，且處理帳號事務的人也不會看這邊

賬號沒有好友，無法找回~沒有別的渠道？

**Comment by chhsiao1981** [comment]
"這邊是討論程式問題的地方，且處理帳號事務的人也不會看這邊"

**Comment by holishing** [comment]
> > ID_GetBack 板置底公告自己看一看，這邊是討論程式問題的地方，且處理帳號事務的人也不會看這邊
> 
> 賬號沒有好友，無法找回~沒有別的渠道？

<del>你自己不看清楚公告我也沒辦法，就當作你帳號沒救吧。</del>更別說這邊不是討論帳號問題的地方了，只是無帳號者好像沒有更好的地方可以問所以勉強回答。

剛才言重了先為此道歉，本來預期你應該可以看到這篇：
https://www.ptt.cc/bbs/ID_GetBack/M.1603329678.A.726.html
但站方似乎做了一些設定讓[部分看板無法用網頁版存取](https://www.ptt.cc/bbs/PttBug/M.1617693303.A.9EF.html)，這部分不知道系統部或站方其他單位有什麼考量?

既然你有了 email 且用他註冊，你理論上最後的希望就只能寄託在這個：
![圖片](https://user-images.githubusercontent.com/19514836/120081908-891e1200-c0f2-11eb-9bc3-63e40804583b.png)

這樣應該就要能領回你的帳號了，如果連 ID 都猜不到就放棄吧

**Comment by hijkzzz** [comment]
> > > ID_GetBack 板置底公告自己看一看，這邊是討論程式問題的地方，且處理帳號事務的人也不會看這邊
> > 
> > 
> > 賬號沒有好友，無法找回~沒有別的渠道？
> 
> ~你自己不看清楚公告我也沒辦法，就當作你帳號沒救吧。~更別說這邊不是討論帳號問題的地方了，只是無帳號者好像沒有更好的地方可以問所以勉強回答。
> 
> 剛才言重了先為此道歉，本來預期你應該可以看到這篇：
> https://www.ptt.cc/bbs/ID_GetBack/M.1603329678.A.726.html
> 但站方似乎做了一些設定讓[部分看板無法用網頁版存取](https://www.ptt.cc/bbs/PttBug/M.1617693303.A.9EF.html)，這部分不知道系統部或站方其他單位有什麼考量?
> 
> 既然你有了 email 且用他註冊，你理論上最後的希望就只能寄託在這個：
> ![圖片](https://user-images.githubusercontent.com/19514836/120081908-891e1200-c0f2-11eb-9bc3-63e40804583b.png)
> 
> 這樣應該就要能領回你的帳號了，如果連 ID 都猜不到就放棄吧

這個功能僅限於找回password
不過還是謝謝了~
