### ISSUE TITLE
可用單一信箱多次認證

### ISSUE THREAD

**Issue by fxfxxxfxx** [ptt/pttbbs#116]
如果用以下格式寄出：

`"B12345678(comment)"@example.com`
(要有雙引號)

一樣會寄到 `B12345678@example.com`
括號內可以填任何值

PTT好像沒有檢查這件事，會被當成不同信箱
所以可以用單一台大信箱多次認證

我有實際測試過 的確能用以前註冊/認證過的信箱再次認證

**Comment by IepIweidieng** [comment]
https://en.wikipedia.org/wiki/Email_address#Local-part

**Comment by wens** [comment]
FTR this was fixed in commit 26b55a03 ("mbbsd: Check register email address harder").
