### ISSUE TITLE
為什麼不支援完整的UTF8？

### ISSUE THREAD

**Issue by Fdhvdu** [ptt/pttbbs#13]
pttbbs/common/sys/utf8.c裡面的utf2ucs沒辦法支援4 byte長度的utf8
難道不支援的原因只是因為要配合用big5編碼的使用者？

**Comment by wens** [comment]
@hungte ?

**Comment by hungte** [comment]
3 byte 就可以完整支援 UCS2了，那個時代所有系統對 >UCS2 的支援都不高，感覺也沒有急迫需求

**Comment by hungte** [comment]
Close since we still don't see urgent needs on this - for example if we do see massive pages or contents that really need UCS4.
