### ISSUE TITLE
小問題*2

### ISSUE THREAD

**Issue by holishing** [ptt/pttbbs#14]
1.
就是post點歌排行榜顯示的名稱不會隨著BBSMNAME而改變
如果不想改太多的話是不是就把 [Ptt流行網] 改成 [點播流行網] 或其他不會用到BBS名字的名稱這樣?

2.
mbbsd/bbs.c第817~824行有提供一個彩色日期的選項

```
    {
#ifdef COLORDATE
	prints(ANSI_COLOR(%d) "%-6.5s" ANSI_RESET,
		(ent->date[3] + ent->date[4]) % 7 + 31, ent->date);
#else
	prints("%-6.5s", ent->date);
#endif
    }
```

但預設是暗彩色,不知道是不是因為為了方便綠色日期跟推文數顏色區分?
不知道有沒有機會另外提供亮彩色選項 ANSI_COLOR(%d) 加上 1; 變成 ANSI_COLOR(1;%d)
還是需要時自己改code即可...orz

目前只有想到：(編譯測試後ok,會不會影響系統效能不知道...至少小站暫時看不出差別...
```
    {
#ifdef COLORDATE
    #ifdef COLORDATE_BRIGHT
        prints(ANSI_COLOR(1;%d) "%-6.5s" ANSI_RESET,
    #else
        prints(ANSI_COLOR(%d) "%-6.5s" ANSI_RESET,
    #endif
    (ent->date[3] + ent->date[4]) % 7 + 31, ent->date);
#else
    prints("%-6.5s", ent->date);
#endif
    }
```
可以自行精簡程式碼...(如果可以的話

**Comment by hungte** [comment]
No.1 Thanks for your suggestion (https://github.com/ptt/pttbbs/commit/be178d2fc4622bea92b53db06b3e48686f9eef3b)
No.2 Not seeing any good reason for this option.
