### ISSUE TITLE
crosspost 四版即毀帳

### ISSUE THREAD

**Issue by jidanni** [ptt/pttbbs#15]
If the user crossposts (^X) more than three times,
one hour later his articles will be deleted,
and he will be charged $1000,
which he is unable to pay.
形同毀帳。

倒不如於第四 crosspost, simply not allow him to post the fourth
crosspost. 比毀掉人家帳號好多了。

且使用者每次 crosspost 都看到同樣警語。
惟某一天超越同文三次門檻即毀帳，
非常不應該的。

**Comment by progheal** [comment]
0. 我只是一個已經泡在批踢踢裡十幾年的路人，不是站長。
1. 來到一個地方不去看那裡的規定那死了活該，而且這還不是藏在哪個小角落的規定，是每次 crosspost 時都會顯示出來的警告。
2. 我實在想不出來除了網宣之外還有什麼東西會需要到同一篇文章轉發到多於三個不同的版面上。網宣的部份在警告中也已提供做法了。
3. 阻擋第四次轉錄會影響轉錄四篇不同且可能無關的文章至同一或不同版面的使用者的權利。規定是「不同看板多次重覆發表或轉錄相似內容之文章」，不應影響非此情形的轉錄，

**Comment by hrchu** [comment]
peace

**Comment by jidanni** [comment]
因系統會記載於該篇底該篇已被該人轉發至哪裡幾次，
故系統已有能力當場阻止。

免永遠毀帳，與 PTT 永遠隔絕該用戶。

如每個月某使用者轉貼某文至某幾板，
均受好評。警語均一致。卻某月轉發如

https://www.facebook.com/events/2179751882250592/permalink/2185003611725419/

至四個性別相關板突然一輩子不允許再用台灣的 PTT.

**Comment by progheal** [comment]
補個早上忘記提的第負一點: 這裡是專門給程式碼的 issue 的，若有站方管理問題請至 PttSuggest 版。

**Comment by jidanni** [comment]
請問該試用者無能張貼全至 PttSuggest 版是否仍有用？

另該價目表
```
4-6 crossposts 1000元
7-9 crossposts 2000元...
```
務必擺在前面警語。
軟體應勿等待消費者誤觸地雷/
掉落陷阱才似乎巧妙的拿出來。
如「停車一小時200元」
均有義務事前告知實額。
連最基本的停車場都做得到，
以免敲竹槓的嫌疑。
這樣才能減少糾紛也符合良心。

另讀者次日查，
```
 作者  [Ptt警察局]
 標題  [報告] 違法報告
 時間  Thu Feb 16 23:05:47 2017
───────────────────────────────────────

站務警察判決：
     ******因Cross-post行為，
違反本站站規，處以罰單處份，特此通知

請到 PttLaw 查詢相關法規資訊，並從主選單進入:
(P)lay【娛樂與休閒】=>(P)ay【Ｐtt量販店 】=> (1)ViolateLaw 繳罰單
以繳交罰單。
```
未料到該處僅見到

```
【 繳罰單中心 】
 ◆ 依照違規次數(1), 你還需要反省 2 天才能繳罰單 [按任意鍵繼續]
```
完全再也看不到初次見到的價目表。
連所欠金額不再透漏給當事人！
請修改程式。

**Comment by jidanni** [comment]
如
https://www.ptt.cc/bbs/transgender/M.1487522744.A.993.html
沒事。但若再加一版就一輩子不能再用 PTT.

**Comment by jidanni** [comment]
Please don't think I'm campaigning for the right to crosspost. I
just think it is unfair for PTT to ban people for life with no human
to appeal to for just one additional ^X (crosspost) whereas anything
less carries absolutely no penalty.

最後讀者見到
```
這是你第 1 次違反本站法規必須繳出 1000 Ptt幣；但你目前只有 621 ，數量不足!!
 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
```
後面完全無補救方法。
未加「如果後悔、寫悔改書，請聯絡誰…」。

**Comment by jidanni** [comment]
也有別人分別貼…
https://www.ptt.cc/bbs/bi-sexual/M.1487675837.A.A1E.html
https://www.ptt.cc/bbs/transgender/M.1487677540.A.787.html
…
未終身遭禁。

**Comment by jidanni** [comment]
建議將
```    　　　　　 欲申訴Cross Post請至Board-Police板```
（見於 PttLegal 進版畫面）複製至信箱該通知函。

**Comment by jidanni** [comment]
找到 https://www.ptt.cc/bbs/Board-Police/M.1487256963.A.FA7.html 原是六版。

**Comment by jidanni** [comment]
發現 Board-Police 版仍能張貼！
http://ppt.cc/j2hf 找到 CP 規定。
如
'第三章  對於違規行為認定權人之認定或處分不服'
只能 Google 到， 未有 Board-Police http 版連出。
我隔那麼久終於找到。
應一開始，信件應列。
另發現
"請至本站「站務建議版」（PttSuggest）提出。"
終於找到
```
 作者  longbow2 (踮起腳尖的親吻)                           看板  Board-Police
 標題  [公告] 對本局開罰不服，得於本板發表文章說明
 時間  Sun Feb 19 02:44:03 2012
```

另
```
 作者  longbow2 (踮起腳尖的親吻)
 標題  [公告] 本板處理程序更動
 時間  Fri Mar  2 01:33:38 2012
```
篇底我會加連結至本建議單。

結果不能 edit. 故特此說：
過程中使用者完全未見到任何申訴管道提示。
唯一選項是繳罰單。無任何 Board-Police 提示。

**Comment by jidanni** [comment]
好我向 Board-Police 版申訴看。
https://www.ptt.cc/bbs/Board-Police/M.1488075622.A.3A2.html

**Comment by jidanni** [comment]
今發現警告文的確文中明列 "連原文共超過四篇就可能會被檢舉" 。

問題是，某使用者，多年轉發活動訊息，
都看到相同警告文。多年 Cross-post 到好多版都沒事，
對警告文就會麻木。
且警告文應明列
```
8.上站次數未滿 60 次即違反 CP 規定者，予以開處罰單後，砍除帳號處分。

9.上站滿 60 次，將依以下CP標準開處罰單：

              05 ~  9 篇：罰單一張。

              10 ~ 19 篇：罰單二張。

              20 ~ 29 篇：罰單三張。

              依此類推。
```
以及一張罰單是多少錢(1000),
未繳就不能貼文章等等均均應列，
使用者才能知道後果。
