### ISSUE TITLE
Mail -> Forward should offer a way to get back out without making changes

### ISSUE THREAD

**Issue by jidanni** [ptt/pttbbs#18]
使用者一旦誤按
```●(F)orward       設定信箱自動轉寄```
就無法離去。連 CTRL-C 會摧毀原設定。

**Comment by holishing** [comment]
「按CTRL-C 會直接取消信箱自動轉寄」這個部份，的確可以調整，

但其實你不小心按到 `●(F)orward 設定信箱自動轉寄`

按兩次Enter或按完一次Enter後選Q，設定就可以完全不會動到了。

**Comment by jidanni** [comment]
連欲查一下即面臨被逼疑似重新設定。
使用者不敢按 Enter, 怕導致重新發確認碼。
只能把整個 Pcmanx ALT-F4 掉，重新登錄。
該 Q 應隨時提供。如 Facebook 每面均具撤退選項…

**Comment by hungte** [comment]
Ctrl-C is the global shortcut to input empty string.
Intended behavior.

The issues on Github are for general program development issues, not site feature request or policy.
Please use PttSuggest for feature requests.
