### ISSUE TITLE
改寫 PTT 用 HBase 來儲存

### ISSUE THREAD

**Issue by kewang** [ptt/pttbbs#2]
https://m.facebook.com/story.php?story_fbid=10208219475071485&id=1440581349&ref=bookmarks

看到今天中午公布的，早上才想到要用 HBase 來改寫，最近會開始分析 schema。

只要 rowkey 做的好，應該會讓整體效能變好。

這樣子擴充性應該會比較好，至少不用一直刪資料，不知道大家覺得如何？

**Comment by wens** [comment]
There's been more than one attempt to find a suitable replacement storage engine,
but lack of time and resources, plus the antiquated code structure resulted in little momentum on the subject.

**Comment by kewang** [comment]
XDDDDD

I want to try it.

**Comment by LivingInPortal** [comment]
Any plan to rewrite Ptt?
Already an impossible mission?

**Comment by hungte** [comment]
This is not a goal for current core developers, especially due to the constraints in hardware setup today. Feel free to make your own version and make a PULL request after done.
