### ISSUE TITLE
Why websocket check origin header?

### ISSUE THREAD

**Issue by SemonCat** [ptt/pttbbs#25]
目前只允許下列站點使用 WebSocket，

然而 https://robertabcd.github.io 已經很久沒有更新了，

是否可以開放其他客戶端連線？

**Comment by robertabcd** [comment]
To answer your title: the origin check is there for security reasons.
To answer your comment: the origin whitelist shouldn't be hardcoded in the source. I plan to make it configurable. After this is done, it becomes an operations question, which is not related to this repository.
