### ISSUE TITLE
特色請求：黑名單功能

### ISSUE THREAD

**Issue by brlin-tw** [ptt/pttbbs#28]
## Rationale
希望能直接在 PTT 上支援目前實作於各 PTT 行動客戶端應用的黑名單功能，讓使用者能夠在瀏覽文章時知道哪些 ID 在黑名單內

這個算是很常用(?)的功能應該要直接實作在站台上

## 實作細節
* 吻合的 ID 顏色調暗
* 吻合 ID 發表的推文文字顏色調暗
* 在文章瀏覽畫面中有快捷鍵（例：Ctrl+B）可以輸入要加進黑名單中的 ID

## Extra
* 像是 Adblock 規則一樣，允許分享自己組建的，針對特定類型使用者的黑名單供他人訂閱使用

**Comment by hungte** [comment]
The issues on Github are for general program development issues, not site feature request or policy.
Please use PttSuggest for feature requests.
