### ISSUE TITLE
Any dataset for PTT comments?

### ISSUE THREAD

**Issue by robhawkins** [ptt/pttbbs#3]
Greetings, is there any sort of PTT dataset or API for accessing the comments similar to the [comments dataset for reddit](https://www.reddit.com/r/datasets/comments/3bxlg7/i_have_every_publicly_available_reddit_comment)?

**Comment by kcwu** [comment]
No such dataset or API and we don't have plan about that in short term.
Actually, comments are stored with articles together and no way to distinguish them reliably.
