### ISSUE TITLE
需要开发一个注册功能吗

### ISSUE THREAD

**Issue by XJawher** [ptt/pttbbs#38]
我访问了好一会你们的这个网站,发现如果我想留言或者想和你们做交流的话是没法做交流的,请问你们需要做一个可登录的功能吗

**Comment by progheal** [comment]
路過回答，這個站是 telnet based, 請由 telnet://ptt.cc 進入。

**Comment by holishing** [comment]
It's recommend to use telnet BBS client like [PCMan](https://github.com/pcman-bbs/pcman-windows/releases) to browse this site.

If you prefer web terminal: https://term.ptt.cc

**Comment by JsonFn** [comment]
建議用ssh加密連線,不要telnet.

**Comment by holishing** [comment]
其實 https://term.ptt.cc 也是 websocket + TLS 加密連線。

另外 [PCMan](https://pcman.ptt.cc) 9.5.0 Beta 也可以用 `wss://ws.ptt.cc/bbs` 加密連到 Ptt

**Comment by onedou** [comment]
@XJawher 这个使用telnet的... http只能看... 我对这种操作始终不习惯

**Comment by holishing** [comment]
https://term.ptt.cc 明明就可以登入發文...

**Comment by onedou** [comment]
现在才发现用HTML模拟出CMD UI了...

**Comment by hungte** [comment]
https://term.ptt.cc is the answer.
