### ISSUE TITLE
How many process can ptt handle?

### ISSUE THREAD

**Issue by LivingInPortal** [ptt/pttbbs#4]
In Linux, a value at /proc/sys/kernel/pid_max handles how many processes it can contain.
On default, it is set to 32768.
But ptt handles over 10 thousands connections at a time.
It means ptt have to open over 10 thousands process at a time too. (If the connection is ssh)
I know there's a program called logind to handle connections in a single process.
I just wonder how ptt handle ssh connections...

**Comment by wens** [comment]
/proc/sys/kernel/pid_max on Ptt is set to 300,000 or something. Don't remember the exact number.

For ssh connections, 3 pids are used per connection, 2 for sshd and 1 for bbs.

**Comment by LivingInPortal** [comment]
Does it mean I can start a DoS on ssh connections?

**Comment by LivingInPortal** [comment]
I forgot sessions on sshd. Forgive me

**Comment by wens** [comment]
Now why would you do that? Furthermore, this has nothing to do with the code in this repository.
