### ISSUE TITLE
About Branch Quantity

### ISSUE THREAD

**Issue by yehochanan0823** [ptt/pttbbs#41]
經過我的計算，此專案資料庫（P.T.T.B.B.S.）共有85個分流（Branch），其中31個來自於原作者（P.T.T.官方）。
因為這個數量有些多，所以希望官方能合併（Merge）一些分流。

**Comment by holishing** [comment]
感覺很多是之前 subversion 時代轉換過來留下來的，點進去看其實也是空的(早就 merge 了)

**Comment by yehochanan0823** [comment]
那麼，那些沒有儲存資料的分流可以刪除吧？

**Comment by holishing** [comment]
有翻過 `ptt.cc` 的 PttCurrent 板以及 `ptt2.cc` 的 PttSvn 板就能理解這些東西都不是毫無意義的歷史記錄吧，自己不太理解刪掉的必要性何在。

**Comment by Yukaii** [comment]
@Hans19980823 想到另一種方式，現在很多 git gui client 都會把階層式分支命名 (feature/feature1、feature/feature2) 顯示成資料夾，如果把沒用到的 branch 重新命名成：old/branch-1、old/branch-2 之類，或許會比較有條理？

**Comment by wens** [comment]
那對 github 或 git cli 沒差, 不過我們確實可以改成 from-svn/* ，然後沒興趣的人就不要抓這些 refspec 了

**Comment by yehochanan0823** [comment]
看起來這個問題的解決方法需要花一些時間去研究了。

**Comment by kcwu** [comment]
我好奇的是, 你的工作流程是怎樣, 很多沒用到的 branch 有造成困擾嗎?
