### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ptt/pttbbs#51]
I would like to point out that identifiers like “[`_LIBBBS_H_`](https://github.com/ptt/pttbbs/blob/65f82aa6534e44c8de14eeb889000d2917cefbfc/include/cmbbs.h#L1 "Update candidate")” and “[`_STATISTIC_H_`](https://github.com/ptt/pttbbs/blob/80eb9e0c6a11007a92ed8bd28e375425a02e8958/include/statistic.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by hungte** [comment]
That correct. Patches welcome.
