### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ptt/pttbbs#52]
Would you like to add more error handling for return values from functions like the following?
* [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [buildchilds](https://github.com/ptt/pttbbs/blob/6461cbbacb868363ecba12fce305ab74bd42e6b0/util/buildAnnounce.c#L15)
* [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [check](https://github.com/ptt/pttbbs/blob/6461cbbacb868363ecba12fce305ab74bd42e6b0/util/showuser.c#L4)
* [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [add_hash](https://github.com/ptt/pttbbs/blob/6461cbbacb868363ecba12fce305ab74bd42e6b0/util/merge_board.c#L38)

**Comment by hungte** [comment]
check is inside utils/chk_us and we don't want to put too much effort on it.

for add_hash and buildchilds, patches are welcomed.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by hungte** [comment]
We did run some source checkers several times I think, but it's more focusing on the running daemons, not utils.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
