### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ptt/pttbbs#53]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
* [copyqueue_append](https://github.com/ptt/pttbbs/blob/6461cbbacb868363ecba12fce305ab74bd42e6b0/mbbsd/announce.c#L78 "copyqueue_append function")
* [substitute_record2](https://github.com/ptt/pttbbs/blob/ef1b000e3aa63c0ba9ef0626c23ca88b169fa013/common/sys/record.c#L117 "substitute_record2 function")
* [Vector_resize](https://github.com/ptt/pttbbs/blob/6461cbbacb868363ecba12fce305ab74bd42e6b0/common/sys/vector.c#L54 "Vector_resize function")

**Comment by hungte** [comment]
Agree, patches are welcomed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/ptt/pttbbs/commit/7167de77b288061a564f2e0fcb8c2985259e47a4 "Remove unnecessary null pointer checks.").
