### ISSUE TITLE
Allow users to freely modify their email address

### ISSUE THREAD

**Issue by wens** [ptt/pttbbs#61]
The system currently does not allow users to freely modify their email address.

If they verified their account using an email address, then if they request a change,
the SYSOP would request they also re-verify their account.

If they verified their account with manual entered personal information, they
do not get to tie an email address to their account.

This whole setup is arcane and inconvenient. For example, it prevents us from
providing password reset services via email, among other things.

Check the code and see what needs to be changed, what might need to be
preserved across modifications, and where and how to log email changes.

**Comment by hungte** [comment]
This is related to a fundamental problem for how the account is treated and trusted today.
And all the issues related to account management will lead to same conclusion - we need to rewrite the account system so it's no longer a single file with limited capacity. An unlimited database is preferred.

**Comment by robertabcd** [comment]
The account verification is being moved out to separate db in https://github.com/ptt/pttbbs/pull/81
This can be allowed after that's done.
Unlimited account database is another story.

**Comment by robertabcd** [comment]
Done
