### ISSUE TITLE
[建議] 使用者 IP 使用累計次數排名

### ISSUE THREAD

**Issue by pgusr** [ptt/pttbbs#66]
能否新增使用者 IP 使用累計次數排名? 比方說, 假設有3個使用者 A, B, 和 C. 其中 

A 使用的 IP 登入有 173.115.224.26, 211.76.137.43, 77.216.252.78, 77.90.103.139, 108.34.127.26.
B 過去使用登入的 IP 有 200.180.145.220, 126.2.91.185
C 登入的 IP 只有 13.53.68.254

依此排名顯示為 

    使用者 | 次數
        A     |    5 
        B     |    2 
        C     |    1 

排名可以依歷史累計(總共使用 IP 累計), 每天(或每個禮拜, 每個月)累計.

**Comment by robertabcd** [comment]
I don't see the value of this feature. I'm going to close this for now.
