### ISSUE TITLE
[Bug] Ptt web search logic error

### ISSUE THREAD

**Issue by hortune** [ptt/pttbbs#78]
When I was using the web search api with the following two requests, there something strange.
The results of the first request should include the one from the second result. (>=100 should fulfill >= 95)
However, the result doesn't fulfill this logic.

https://www.ptt.cc/bbs/Boy-Girl/search?q=recommend%3A95
```
爆
Re: [討論] 女生最討厭男網友問什麼？
FISHBONE0914
⋯
3/25
爆
Re: [討論] 女生最討厭男網友問什麼？
sumade
⋯
3/25
爆
[求助] 在一起沒多久就想分手
klyuch
⋯
```

https://www.ptt.cc/bbs/Boy-Girl/search?q=recommend%3A100
```
爆
Re: [討論] 這個影片是不是仇女???
yy10322
⋯
3/26
爆
Re: [討論] 所以你們有純友誼的女生朋友嗎？
beeeemo
⋯
3/26
爆
Re: [討論] 女生最討厭男網友問什麼？
FISHBONE0914
⋯
3/25
爆
Re: [討論] 女生最討厭男網友問什麼？
sumade
⋯
```

**Comment by holishing** [comment]
related project should be: https://github.com/ptt/pttweb

**Comment by hortune** [comment]
thanks
