### ISSUE TITLE
使用 Mac 連上 term.ptt.cc，在發表文章/發送站內信時按下 ^ + X 沒有任何反應

### ISSUE THREAD

**Issue by LZong-tw** [ptt/pttbbs#84]
同標題，
OS： macOS 10.15.5(19F101)
瀏覽器：Chrome 83.0.4103.116

**Comment by holishing** [comment]
那是 Ctrl+X

**Comment by LZong-tw** [comment]
沒錯，^ 就是 control，其他像是 ^ + P、^ + Q、^ + Z、^ + G、^ + C 的指令都能正確觸發，只有 ^ + X 怎麼按就是沒動靜

**Comment by robertabcd** [comment]
這應該非 BBS 端的問題，屬於瀏覽程式問題，是屬於這個 repo：https://github.com/robertabcd/PttChrome
剛測試同樣環境下無此現象。請您使用無痕瀏覽關閉所有外掛套件看是不是仍有此問題。或是確認是否系統設定有將此快速鍵綁定至其他功能。

**Comment by LZong-tw** [comment]
謝謝 ，我用了無痕還是一樣，但換到 Safari 就正常了，應該是 Chrome 這邊的問題
