### ISSUE TITLE
[propose] Replace .PASSWDS with DB (mongodb)

### ISSUE THREAD

**Issue by chhsiao1981** [ptt/pttbbs#91]
.PASSWDS is one file recording all users' critical information.

In current setting (ssh/telnet/ws), we initialize userec in the login
to minimize reading the file.

However, it will be difficult for web-based service because
it's hard to keep track of userec without reading .PASSWD.
(.PASSWD is one gigantic file recording all the users.
 It's not feasible to know whether data of one user is updated
 just by looking at the mtime of the file.)

.PASSWDS is with fixed size / fixed columns and is easy to migrate to db-based (by uid and by userid) storage.

We can follow the typical setup for the smooth upgrade:

Read: try to get data from db first, if success: return data. otherwise, get data from file and write to db, return data.
Write: try both on file and db.

The followings are the files / functions using .PASSWDS (fn_passwd / FN_PASSWD):

util/mailangel.c: 57 (readData): fread(&user, sizeof(userec_t), 1, fp)
util/uhash_loader.c: 118 (fill_uhash): for (mimage = fimage; usernumber < fd; mimage += sizeof(userec_t)) (read)
util/tunepasswd.c: (當 MAX_USERS 長大時. 要把 .PASSWD 跟著長大. db 上可以不考慮這件事情～)
util/xchatd.c: 195: get_record(FN_PASSWD, acct, sizeof(ACCT), id)
util/angel.c: 70: fread(&user, sizeof(user), 1, fp)
daemon/regmaild/regmaild.c: 232: read(fd, &xuser, sizeof(xuser))
mbbsd/admin.c:397: fread(&user, sizeof(user), 1, fp1)

util/writemony.c (main)
common/bbs/passwd.c:
    passwd_update_money
    passwd_update
    passwd_query

mbbsd/register.c:408 if ((fd = OpenCreate(fn_passwd, O_RDWR)) == -1)
    (not exactly sure why it's there, looks like it just want to ensure that fn_passwd exists, but forgot to close fd)

The PR will include tests.

**Comment by wens** [comment]
> However, it will be difficult for web-based service because
> it's hard to keep track of userec without reading .PASSWD.

This doesn't quite make sense. Regardless of the backend storage, you still need to read out the data,
be it a blob that expands into multiple fields, or a database system that presents the fields to you.

> (.PASSWD is one gigantic file recording all the users.
> It's not feasible to know whether data of one user is updated
> just by looking at the mtime of the file.)

It would make more sense if you explained "why" you need to know whether individual users were updated.

**Comment by chhsiao1981** [comment]
hi @wens ～

The proposed web-based service are divided with 2 layers,
including:
  backend: the same machine as the original pttbbs server, intending to directly access the data in shared-mem and files.
  middleware: a separate machine (hopefully besides the original pttbbs server) dealing with frontend and communicate
      with the backend.

middleware is designed to be easily horizontally scalable with easily horizontally scalable db.

For the file-based data in pttbbs, we can have some permanent-db in middleware as the cache to avoid requesting data from backend/pttbbs server too often.
What I think of the cache-validation mechanism is to compare the mtime of the file and the last-update-time in the middleware. => need to know whether individual users were updated.

**Comment by chhsiao1981** [comment]
> > However, it will be difficult for web-based service because
> > it's hard to keep track of userec without reading .PASSWD.
> 
> This doesn't quite make sense. Regardless of the backend storage, you still need to read out the data,
> be it a blob that expands into multiple fields, or a database system that presents the fields to you.
> 

hi @wens ～

Though we still need to read out the data,
but I thought that reading data from horizontal-scalable db with replica through intranet
are much safer than reading data from 1 local file.
(Or now we are using m2ssd and reading data from file is not any more huge issue？～)

**Comment by wens** [comment]
Doesn't that mean you end up polling 2M number of users say every minute?
That's not much better than just throwing data away every minute.
Just cache it for 1 minute and re-fetch when it expires.
Or maybe just don't cache it at this time.
Wait until it actually becomes a performance bottleneck.

**Comment by wens** [comment]
> > > However, it will be difficult for web-based service because
> > > it's hard to keep track of userec without reading .PASSWD.
> > 
> > 
> > This doesn't quite make sense. Regardless of the backend storage, you still need to read out the data,
> > be it a blob that expands into multiple fields, or a database system that presents the fields to you.
> 
> hi @wens ～
> 
> Though we still need to read out the data,
> but I thought that reading data from horizontal-scalable db with replica through intranet

It will not be horizontally scaled, but likely sitting on the same machine.
We simply do not have machines to do "horizontally scaled systems".
So you are trading single host performance and complexity for unachievable
horizontal scalability. I doubt it would perform better.

> are much safer than reading data from 1 local file.

How is that? If you are reading through intranet it will be equally fast.
If the main machine breaks down, well the whole site will be down anyway.
And if the new system keeps on running with state updates, then you end
up with data synchronization issues.

I think "safer" is not the word you are looking for.

> (Or now we are using m2ssd and reading data from file is not any more huge issue？～)

AFAIAC you should be more focused on getting the new system up with basic features,
and worry about performance bottlenecks later.

**Comment by chhsiao1981** [comment]
> > > > However, it will be difficult for web-based service because
> > > > it's hard to keep track of userec without reading .PASSWD.
> > > 
> > > 
> > > This doesn't quite make sense. Regardless of the backend storage, you still need to read out the data,
> > > be it a blob that expands into multiple fields, or a database system that presents the fields to you.
> > 
> > 
> > hi @wens ～
> > Though we still need to read out the data,
> > but I thought that reading data from horizontal-scalable db with replica through intranet
> 
> It will not be horizontally scaled, but likely sitting on the same machine.
> We simply do not have machines to do "horizontally scaled systems".
> So you are trading single host performance and complexity for unachievable
> horizontal scalability. I doubt it would perform better.
> 
> > are much safer than reading data from 1 local file.
> 
> How is that? If you are reading through intranet it will be equally fast.
> If the main machine breaks down, well the whole site will be down anyway.
> And if the new system keeps on running with state updates, then you end
> up with data synchronization issues.
> 
> I think "safer" is not the word you are looking for.
> 
> > (Or now we are using m2ssd and reading data from file is not any more huge issue？～)
> 
> AFAIAC you should be more focused on getting the new system up with basic features,
> and worry about performance bottlenecks later.

Sounds good～ I'll close the issue for now～
