### ISSUE TITLE
Possible one more i++ in cmsys.strip_nonebig5？

### ISSUE THREAD

**Issue by chhsiao1981** [ptt/pttbbs#94]
https://github.com/ptt/pttbbs/blob/master/common/sys/string.c#L283

0xFFFD happened in u2b.
We can paste thai characters in utf8-terminal
and get 0xFFFD.

strip_nonebig5 affects 
title in mbbsd/bbs.readdoent  and
currutmp->nickname in setup_utmp.

**Comment by IepIweidieng** [comment]
According to `common/sys/big5.c`:
- Unicode code points without the corresponding Big5-UAO code point are always converted to `0xfffd` (see `u2b_table`).
- Big5-UAO code points `0xfeff`-`0xffff` are left unchanged when converted into Unicode (see `b2u_table`).

Consider the case for `strip_nonebig5`: `str` is `"\xff\xfdQ"` and `maxlen` > `3`.

When `i` is `0`, both `else if(str[i]==255) {` and `if(251<=str[i+1] && str[i+1]<=254) {` hold, and the first `i++` following them skips the byte `\xff`.

`if(i+1<maxlen && str[i+1])` also holds, and the second `i++` skips the byte `\xfd`.

However, the `for` loop also performs `i++` after the `continue` and makes the byte `Q` ignored.

Therefore, the second `i++` is redundant and erroneous. It makes the byte following `"\xff\xfd"` ignored.

Note that the UTF-8 encoding of `U+FFFD` is `ef bf bd` (binary: `11101111 10111111 10111101`), but UTF-8 is only used for handling input and output for UTF-8 clients and is converted to Unicode code points internally, so it should be irrelevant to this issue.

Function usages of `strip_nonebig5`:
- `mbbsd/mbbsd.c`: `setup_utmp` for user nickname display
- `mbbsd/bbs.c`: `readdoent` for article title display

Only the displayed strings are processed through `strip_nonebig5`, while the strings which are stored to the disk are not affected.
