### ISSUE TITLE
[資訊] 如果你收不到認證信的話

### ISSUE THREAD

**Issue by PichuChen** [ptt/pttbbs#98]
假如你是用 GCP 或者是某些雲端服務的話，可以先測試

`telnet gmail-smtp-in.l.google.com. 25` (或是 dig gmail.com 找個喜歡的 mail server 測試)

假如沒有看到像是 220 xxxxxx 之類的訊息的話，那代表這個提供商預設 Ban 掉 Port 25。

看起來應該是在 Postfix 裡面把預設連線到 25 的設定改掉就行了，不過我找了一下沒找到設定，所以我的作法是把 GCP 改掉。

**Comment by chhsiao1981** [comment]
https://cloud.google.com/compute/docs/tutorials/sending-mail

(I don't think this issue is related to this repository～)

**Comment by PichuChen** [comment]
也需要考慮內建 smtp 讓他走 port 465 之類的。

**Comment by robertabcd** [comment]
It sounds like you are trying to run a site on cloud platforms, who banned port 25. As this is not an issue of the code, I'm closing the issue.
